
name: flutter_web_home
description: "Lyu Web Home"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dynamic_color: ^1.7.0
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.6
  flutter_markdown: ^0.7.2+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
      
  assets:
  - ./web/assets/Article.png
  - ./web/assets/files.json
  - ./web/assets/article/欢迎.md